version: "3.9"

services:
  backend:
    build: ./backend
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - linktree-network

  frontend:
    build: ./linktree-frontend
    container_name: vite_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./linktree-frontend:/frontend
      - /frontend/node_modules
    environment:
      - VITE_BACKEND_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - linktree-network

networks:
  linktree-network:
    driver: bridge
